### ISSUE TITLE
Fixing two errors when knitting index.rmd

### ISSUE THREAD

**Issue by oustella** [tbradley1013/dragondown#2]
Encountered two errors when knitting PDF from `index.rmd` after making sure RStudio, TinyTeX, Pandoc, and all packages are up to date as of Feb 2022.

1. `! LaTeX Error: Environment CSLReferences undefined.`

2. `! Undefined control sequence.
<argument> @{} >{\centering \arraybackslash 
                                            }p{(\columnwidth - 6\tabcolsep )...
l.572 ...mnwidth - 6\tabcolsep) * \real{0.36}}@{}}`

I have created a pull request #1 to fix them based on solutions for similar errors encountered by others.

**Comment by tbradley1013** [comment]
Closed with #1
